version: 2
defaults: &defaults
  machine:
    image: circleci/classic:201708-01

  working_directory: ~/ussd_airflow

aws_setup: &aws_setup
    run:
        name: configure aws
        command: |
          sudo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ./devops/scripts/aws_credentials.sh

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - *aws_setup

      - run:
          name: start the containers
          command: |
            docker-compose up -d
            sleep 10
            curl --retry 20 --retry-delay 5 -v http://localhost:8007

      - run:
          name: Running tests
          command: |
            docker-compose run app bash -c 'coverage run --omit=*test*,*ven* manage.py test && bash <(curl -s https://codecov.io/bash) && python-codacy-coverage -r coverage.xml'
  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: deploying
          command: |
            make deploy version=$CIRCLE_TAG



workflows:
  version: 2
  ci:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

