version: 2
defaults: &defaults
  machine:
    image: circleci/classic:201708-01

  working_directory: ~/ussd_airflow

aws_setup: &aws_setup
    run:
        name: configure aws
        command: |
          sudo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ./devops/scripts/aws_credentials.sh

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - *aws_setup

      - run:
          name: Running tests
          command: |
            make test use_cov=yes report_cov=yes
  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: deploying
          command: |
            make deploy version=$CIRCLE_TAG



workflows:
  version: 2
  ci:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

